# Generated by Django 5.1.1 on 2024-11-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_password'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='tipo_entrega',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('local', 'Local')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_entrega',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('local', 'Local')], max_length=10, null=True),
        ),
    ]
