# Generated by Django 5.1.1 on 2024-11-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_descuento_fin_alter_descuento_inicio'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_producto',
            name='ingredientes',
            field=models.ManyToManyField(null=True, related_name='carritos_productos', to='menu.ingrediente'),
        ),
    ]
