# Generated by Django 5.1.1 on 2024-11-16 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_producto_tipo_ingrediente'),
        ('ventas', '0002_alter_carrito_producto_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_producto_extra',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='venta_producto_extra',
            name='venta_producto',
        ),
        migrations.RemoveField(
            model_name='carrito_producto',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='venta_producto',
            name='ingredientes',
        ),
        migrations.CreateModel(
            name='Carrito_Producto_Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('Ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_productos', to='menu.ingrediente')),
                ('carrito_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='ventas.carrito_producto')),
            ],
            options={
                'verbose_name': 'Carrito_Producto_Ingrediente',
                'verbose_name_plural': 'Carritos_Productos_Ingredientes',
                'db_table': 'carritos_productos_ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Venta_Producto_Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_productos', to='menu.ingrediente')),
                ('venta_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='ventas.venta_producto')),
            ],
            options={
                'verbose_name': 'Venta_Producto_Ingredientes',
                'verbose_name_plural': 'Ventas_Productos_Ingredientes',
                'db_table': 'ventas_productos_ingredientes',
            },
        ),
        migrations.DeleteModel(
            name='Carrito_Producto_Extra',
        ),
        migrations.DeleteModel(
            name='Venta_Producto_Extra',
        ),
    ]
