# Generated by Django 5.1.1 on 2024-11-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_descuento_fin_alter_descuento_inicio'),
        ('ventas', '0002_carrito_direccion_carrito_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta_producto',
            name='ingredientes',
            field=models.ManyToManyField(null=True, related_name='ventas_productos', to='menu.ingrediente'),
        ),
    ]
