# Generated by Django 5.1.1 on 2024-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_producto_extra_extra_and_more'),
        ('ventas', '0004_carrito_producto_seleccionado'),
    ]

    operations = [
    ]
