# Generated by Django 5.1.1 on 2024-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_merge_20241125_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_producto',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='carrito_producto',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
    ]
