# Generated by Django 5.1.1 on 2024-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='modo',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('bot', 'Bot')], default='empleado', max_length=10),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='por',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado')], default='cliente', max_length=10),
        ),
    ]
