# Generated by Django 5.1.1 on 2024-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='url_redireccion',
            field=models.ImageField(upload_to='anuncios/'),
        ),
    ]
