# Generated by Django 5.1.1 on 2024-10-02 00:44

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_contraseña_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(error_messages={'unique': 'Ya existe una cuenta registrada con este correo'}, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='contraseña', max_length=128),
        ),
    ]
