# Generated by Django 5.1.1 on 2024-11-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='lon',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
    ]
