# Generated by Django 5.1.1 on 2024-11-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='predeterminada',
            field=models.BooleanField(default=False),
        ),
    ]
