# Generated by Django 5.1.1 on 2024-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_direccion_lat_alter_direccion_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='indicaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
