# Generated by Django 5.1.1 on 2024-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_direccion_predeterminada'),
        ('usuarios', '0008_alter_direccion_indicaciones_alter_direccion_lat_and_more'),
    ]

    operations = [
    ]
