# Generated by Django 5.1.1 on 2024-10-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_descuento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='productos',
        ),
        migrations.AddField(
            model_name='descuento',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(default='Descuento', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu.descuento'),
        ),
    ]
