# Generated by Django 5.1.1 on 2024-10-09 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_descuento_fin_alter_descuento_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='url_foto',
            field=models.ImageField(upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fin',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 6, 41, 34, 186772)),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 6, 41, 34, 186772)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_foto',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
