# Generated by Django 5.1.1 on 2024-10-09 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_categoria_url_foto_alter_descuento_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='url_foto',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fin',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 8, 19, 19, 564980)),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='inicio',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 8, 19, 19, 564980)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_foto',
            field=models.CharField(max_length=256),
        ),
    ]
