# Generated by Django 5.1.1 on 2024-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_descuento_fin_alter_descuento_inicio'),
        ('menu', '0011_remove_tipo_ingrediente_mensaje_and_more'),
    ]

    operations = [
    ]
