# Generated by Django 5.1.1 on 2024-10-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0003_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=35)),
                ('clave', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=85)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
    ]
